# Generated by Django 5.2.8 on 2026-09-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('transport', 'Transport'), ('facilities', 'Facilities'), ('fees', 'Fees'), ('request', 'Request'), ('other', 'Other')], default='other', max_length=12),
        ),
    ]
