# Generated by Django 5.2.8 on 2026-09-11 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SAAS_admin', '0005_school_owner_field'),
        ('School_Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=120)),
                ('action', models.CharField(max_length=40)),
                ('target', models.CharField(max_length=200)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_audit_logs', to='SAAS_admin.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.CharField(blank=True, default='', max_length=254)),
                ('experience', models.CharField(blank=True, default='', max_length=200)),
                ('stage', models.CharField(choices=[('new', 'New'), ('shortlisted', 'Shortlisted'), ('interviewed', 'Interviewed'), ('offered', 'Offer made'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='new', max_length=12)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='SAAS_admin.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveIntegerField(default=1)),
                ('scheduled_on', models.DateField()),
                ('scheduled_at', models.CharField(blank=True, default='', max_length=10)),
                ('interviewer', models.CharField(blank=True, default='', max_length=150)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('scheduled', 'Scheduled'), ('passed', 'Passed'), ('failed', 'Failed'), ('no_show', 'No show')], default='scheduled', max_length=10)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='SAAS_admin.school')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='HR.jobapplication')),
            ],
            options={
                'ordering': ['scheduled_on', 'round_no'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('openings', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, default='')),
                ('posted_on', models.DateField()),
                ('closes_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('filled', 'Filled')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_job_postings', to='SAAS_admin.school')),
            ],
            options={
                'ordering': ['-posted_on'],
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='HR.jobposting'),
        ),
        migrations.CreateModel(
            name='OnboardingChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_tasks', to='SAAS_admin.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_tasks', to='School_Admin.staffmember')),
            ],
            options={
                'ordering': ['is_done', 'due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('permanent', 'Permanent'), ('probation', 'Probation'), ('contract', 'Fixed-term contract'), ('part_time', 'Part-time'), ('visiting', 'Visiting')], default='permanent', max_length=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=10)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_contracts', to='SAAS_admin.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='School_Admin.staffmember')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='StaffDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('certification', 'Certification'), ('contract', 'Contract'), ('cnic', 'CNIC / ID'), ('degree', 'Degree / transcript'), ('other', 'Other')], default='certification', max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('number', models.CharField(blank=True, default='', max_length=100)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('file_url', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_documents', to='SAAS_admin.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_documents', to='School_Admin.staffmember')),
            ],
            options={
                'ordering': ['expiry_date', 'staff__full_name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('workshop', 'Workshop'), ('course', 'Course'), ('certification', 'Certification'), ('conference', 'Conference')], default='workshop', max_length=15)),
                ('provider', models.CharField(blank=True, default='', max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cost_per_head', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_programs', to='SAAS_admin.school')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=30)),
                ('reviewer', models.CharField(blank=True, default='', max_length=150)),
                ('scores', models.JSONField(blank=True, default=dict)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('strengths', models.TextField(blank=True, default='')),
                ('improvements', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=10)),
                ('finalized_by', models.CharField(blank=True, default='', max_length=120)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='SAAS_admin.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='School_Admin.staffmember')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('staff', 'period'), name='unique_appraisal_per_staff_period')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half day'), ('leave', 'On leave')], default='present', max_length=10)),
                ('unpaid', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('marked_by', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_attendance', to='SAAS_admin.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='School_Admin.staffmember')),
            ],
            options={
                'ordering': ['-date', 'staff__full_name'],
                'constraints': [models.UniqueConstraint(fields=('staff', 'date'), name='unique_attendance_per_staff_day')],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('entitled', models.DecimalField(decimal_places=1, default=20, max_digits=5)),
                ('carried_over', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('used', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('unpaid_used', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='SAAS_admin.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='School_Admin.staffmember')),
            ],
            options={
                'ordering': ['-year', 'staff__full_name'],
                'constraints': [models.UniqueConstraint(fields=('staff', 'year'), name='unique_leave_balance_per_staff_year')],
            },
        ),
        migrations.CreateModel(
            name='PayrollInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=30)),
                ('present_days', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('absent_unpaid_days', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('paid_leave_days', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('late_marks', models.PositiveIntegerField(default=0)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('fed_to_payroll', models.BooleanField(default=False)),
                ('fed_by', models.CharField(blank=True, default='', max_length=120)),
                ('fed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_inputs', to='SAAS_admin.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_inputs', to='School_Admin.staffmember')),
            ],
            options={
                'ordering': ['-created_at', 'staff__full_name'],
                'constraints': [models.UniqueConstraint(fields=('staff', 'period'), name='unique_payroll_input_per_staff_period')],
            },
        ),
        migrations.CreateModel(
            name='TrainingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='enrolled', max_length=10)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('certificate_ref', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_enrollments', to='SAAS_admin.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='School_Admin.staffmember')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='HR.trainingprogram')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('program', 'staff'), name='unique_enrollment_per_program_staff')],
            },
        ),
    ]
