# Generated by Django 5.2.8
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_owner', '0001_initial'),
    ]

    operations = [
        # Chains are created with just a name now; the owner account is
        # assigned afterwards from the operator console.
        migrations.AlterField(
            model_name='chain',
            name='owner',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='owned_chain',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
