# Generated by Django 5.2.8 on 2026-09-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('package', models.CharField(choices=[('Starter', 'Starter'), ('Growth', 'Growth'), ('Enterprise', 'Enterprise')], default='Starter', max_length=20)),
                ('students', models.PositiveIntegerField(default=0)),
                ('renewal', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('suspended', 'Suspended')], default='trial', max_length=20)),
                ('contact', models.CharField(blank=True, default='—', max_length=120)),
                ('email', models.CharField(blank=True, default='—', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
