# Generated by Django 5.2.8 on 2026-09-09 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAS_admin', '0003_announcement_impersonationlog_invoice_supportticket_and_more'),
        ('school_owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='school_owner.chain'),
        ),
    ]
