# Generated by Django 5.2.8
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_owner_to_owners(apps, schema_editor):
    """Move the single School.owner FK into the new owners M2M."""
    School = apps.get_model('SAAS_admin', 'School')
    for school in School.objects.exclude(owner__isnull=True).only('id', 'owner_id'):
        school.owners.add(school.owner_id)


def uncopy_owners_to_owner(apps, schema_editor):
    """Best-effort reverse: put the first owner back on the FK."""
    School = apps.get_model('SAAS_admin', 'School')
    for school in School.objects.all().prefetch_related('owners'):
        first = school.owners.first()
        if first is not None:
            school.owner_id = first.pk
            school.save(update_fields=['owner'])


class Migration(migrations.Migration):

    dependencies = [
        ('SAAS_admin', '0005_school_owner_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # A school can have several owners (the console warns before a
        # second owner is added). Temporary related_name until the old FK
        # (which owns 'owned_schools') is removed.
        migrations.AddField(
            model_name='school',
            name='owners',
            field=models.ManyToManyField(
                blank=True,
                related_name='owned_schools_m2m',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(copy_owner_to_owners, uncopy_owners_to_owner),
        migrations.RemoveField(
            model_name='school',
            name='owner',
        ),
        migrations.AlterField(
            model_name='school',
            name='owners',
            field=models.ManyToManyField(
                blank=True,
                related_name='owned_schools',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
