# Generated by Django 5.2.8 on 2026-09-11 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SAAS_admin', '0005_school_owner_field'),
        ('School_Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=120)),
                ('action', models.CharField(max_length=40)),
                ('target', models.CharField(max_length=200)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='SAAS_admin.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], default='cash', max_length=10)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_accounts', to='SAAS_admin.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DefaulterFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('called', 'Called'), ('no_answer', 'No answer'), ('promised', 'Promised to pay'), ('visited', 'Parent visited school'), ('settled', 'Cleared / paid')], default='called', max_length=12)),
                ('promised_on', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('followed_up_by', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='SAAS_admin.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='School_Admin.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('vendor_payment', 'Vendor payment'), ('utility', 'Utility bill'), ('salary', 'Salary'), ('rent', 'Rent'), ('other', 'Other')], default='vendor_payment', max_length=15)),
                ('vendor', models.CharField(blank=True, default='', max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank transfer'), ('cheque', 'Cheque'), ('online', 'Online')], default='cash', max_length=10)),
                ('paid_on', models.DateField()),
                ('reference_no', models.CharField(blank=True, default='', max_length=60)),
                ('details', models.TextField(blank=True, default='')),
                ('recorded_by', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='SAAS_admin.school')),
            ],
            options={
                'ordering': ['-paid_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncomeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('source', models.CharField(choices=[('rent', 'Rent'), ('canteen', 'Canteen'), ('donation', 'Donation'), ('sale', 'Uniform / books sale'), ('other', 'Other')], default='other', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank transfer'), ('cheque', 'Cheque'), ('online', 'Online')], default='cash', max_length=10)),
                ('received_on', models.DateField()),
                ('receipt_no', models.CharField(blank=True, default='', max_length=40)),
                ('details', models.TextField(blank=True, default='')),
                ('recorded_by', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_entries', to='SAAS_admin.school')),
            ],
            options={
                'ordering': ['-received_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Money in'), ('out', 'Money out')], default='in', max_length=3)),
                ('source_type', models.CharField(choices=[('fee_payment', 'Fee payment'), ('income', 'Other income'), ('expense', 'Expense'), ('refund', 'Refund')], max_length=15)),
                ('source_id', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entry_date', models.DateField()),
                ('description', models.CharField(blank=True, default='', max_length=240)),
                ('reconciled', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('reconciled_by', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='Accountant.cashaccount')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='SAAS_admin.school')),
            ],
            options={
                'ordering': ['-entry_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=10)),
                ('approved_by', models.CharField(blank=True, default='', max_length=120)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_periods', to='SAAS_admin.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_items', to='SAAS_admin.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_items', to='School_Admin.staffmember')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Accountant.payrollperiod')),
            ],
            options={
                'ordering': ['staff__full_name'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('refund', 'Refund'), ('adjustment', 'Adjustment')], default='refund', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='requested', max_length=10)),
                ('requested_by', models.CharField(blank=True, default='', max_length=120)),
                ('approved_by', models.CharField(blank=True, default='', max_length=120)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, default='', max_length=300)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='School_Admin.studentfeeinvoice')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='SAAS_admin.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='School_Admin.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='cashaccount',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_cash_account_per_school'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(fields=('source_type', 'source_id'), name='unique_ledger_entry_per_source'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.UniqueConstraint(fields=('school', 'period'), name='unique_payroll_period_per_school'),
        ),
        migrations.AddConstraint(
            model_name='payrollitem',
            constraint=models.UniqueConstraint(fields=('period', 'staff'), name='unique_payroll_item_per_staff'),
        ),
    ]
