# Generated by Django 5.2.8 on 2026-09-11 18:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SAAS_admin', '0005_school_owner_field'),
        ('School_Admin', '0002_alter_complaint_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=150)),
                ('guardian_name', models.CharField(blank=True, default='', max_length=150)),
                ('guardian_phone', models.CharField(blank=True, default='', max_length=30)),
                ('interested_grade', models.CharField(blank=True, default='', max_length=50)),
                ('source', models.CharField(choices=[('walk_in', 'Walk-in'), ('phone', 'Phone'), ('online', 'Online'), ('referral', 'Referral'), ('other', 'Other')], default='walk_in', max_length=12)),
                ('stage', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('site_visit', 'Site visit'), ('applied', 'Applied'), ('enrolled', 'Enrolled'), ('dropped', 'Dropped')], default='new', max_length=12)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_note', models.CharField(blank=True, default='', max_length=300)),
                ('notes', models.TextField(blank=True, default='')),
                ('assigned_to', models.CharField(blank=True, default='', max_length=120)),
                ('created_by', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fd_enquiry', to='School_Admin.admissionapplication')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fd_enquiries', to='SAAS_admin.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fd_enquiries', to='School_Admin.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=120)),
                ('action', models.CharField(max_length=40)),
                ('target', models.CharField(max_length=200)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fd_audit_logs', to='SAAS_admin.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=150)),
                ('contact', models.CharField(blank=True, default='', max_length=30)),
                ('id_number', models.CharField(blank=True, default='', max_length=60)),
                ('purpose', models.CharField(choices=[('admission', 'Admission enquiry'), ('meeting', 'Meeting staff'), ('parent', 'Parent / guardian'), ('delivery', 'Delivery'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='other', max_length=12)),
                ('whom_to_meet', models.CharField(blank=True, default='', max_length=120)),
                ('badge_no', models.CharField(blank=True, default='', max_length=30)),
                ('entered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
                ('handled_by', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fd_visitor_logs', to='SAAS_admin.school')),
            ],
            options={
                'ordering': ['-entered_at'],
            },
        ),
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_no', models.CharField(max_length=30)),
                ('pass_type', models.CharField(choices=[('student_early', 'Student early leave'), ('visitor', 'Visitor pass'), ('vehicle', 'Vehicle'), ('goods', 'Goods')], default='student_early', max_length=15)),
                ('visitor_name', models.CharField(blank=True, default='', max_length=150)),
                ('contact', models.CharField(blank=True, default='', max_length=30)),
                ('reason', models.CharField(max_length=300)),
                ('issued_to', models.CharField(blank=True, default='', max_length=150)),
                ('issued_by', models.CharField(blank=True, default='', max_length=120)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_return', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='active', max_length=12)),
                ('remarks', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fd_gate_passes', to='SAAS_admin.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fd_gate_passes', to='School_Admin.student')),
            ],
            options={
                'ordering': ['-issued_at'],
                'constraints': [models.UniqueConstraint(fields=('school', 'pass_no'), name='unique_gate_pass_no_per_school')],
            },
        ),
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(max_length=30)),
                ('holder_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], default='student', max_length=10)),
                ('holder_name', models.CharField(max_length=150)),
                ('holder_line', models.CharField(blank=True, default='', max_length=120)),
                ('admission_no', models.CharField(blank=True, default='', max_length=40)),
                ('guardian_phone', models.CharField(blank=True, default='', max_length=30)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('printed', 'Printed')], default='draft', max_length=10)),
                ('remarks', models.CharField(blank=True, default='', max_length=300)),
                ('created_by', models.CharField(blank=True, default='', max_length=120)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fd_id_cards', to='SAAS_admin.school')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fd_id_cards', to='School_Admin.staffmember')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fd_id_cards', to='School_Admin.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('school', 'card_no'), name='unique_id_card_no_per_school')],
            },
        ),
    ]
